---
base_dir: /home/bumblebee/server-cicd

runner_install_dir: "{{ base_dir }}/actions-runner"
github_org: BenSuskins

runner_dependencies:
  - ansible
  - terraform

special_containers: []

containers: []
