---
base_dir: /home/docker/server-docker

special_containers:
  - homepage

containers:
  # MCP
  - mcpjungle
  # Apps
  - family-hub
  - pubgolf-backend
  - pubgolf-frontend
  - wedding-db
  - wedding-db-backup
  - wedding
  # Infrastructure
  - adguard
  - cloudflare-ddns
