---
base_dir: /home/mediaserver/server-mediaserver
mount_nas: true

containers:
  # Streaming
  - plex
  # Media management
  - sonarr
  - radarr
  - bazarr
  - seerr
  - prowlarr
  - sportarr
  - profilarr
  # Downloads
  - gluetun
  - qbittorrent
  - flaresolverr
  - doplarr
  - metube
  - open-books
  - shelfmark
