---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks
###########################
#      Developer        #
###########################
- Developer:
    - Github:
        - abbr: GH
          href: 'https://github.com/'
          icon: si-github
    - Cloudflare:
        - abbr: CF
          href: 'https://cloudflare.com/'
          icon: si-cloudflare
