groups:
  - name: pubgolf_alerts
    rules:
      - alert: PubgolfHighHttp5xxRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[1m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High 5xx error rate"
          description: "More than 5% of requests are failing with 5xx responses."

      - alert: PubgolfHighResponseLatency
        expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[1m])) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response latency"
          description: "95th percentile response time is over 1 second."

      - alert: PubgolfJVMHeapUsageHigh
        expr: jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"} > 0.85
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High JVM heap usage"
          description: "Heap usage is above 85%."
