{
 "title": "TrueNAS",
 "tags": [
  "homelab",
  "infrastructure"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cpu", "query": { "query": "label_values(cpu_usage,cpu)" } },
   { "name": "disk", "query": { "query": "label_values(disk_io,disk)" } },
   {
    "name": "interface",
    "query": {
     "query": "label_values(interface_io,interface)"
    }
   },
   {
    "name": "services",
    "query": {
     "query": "label_values(services_cpu,service)"
    }
   },
   {
    "name": "mountpoint",
    "query": {
     "query": "label_values(disk_bytes_used,mountpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "system_load", "legendFormat": "{{kind}}" }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "cpu_frequency{cpu=~\"$cpu\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "cpu_temperature{cpu=~\"$cpu\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "physical_memory", "legendFormat": "{{kind}}" }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "interface_io{interface=~\"$interface\"}",
     "legendFormat": "{{interface}} - {{op}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "processes", "legendFormat": "{{kind}}" }
   ]
  },
  {
   "title": "Pool State",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "zfs_pool > 0", "legendFormat": "{{pool}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uptime", "legendFormat": "synced" }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "cpu_total", "legendFormat": "{{kind}}" }
     ]
    },
    {
     "title": "CPU frequency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "cpu_frequency{cpu=~\"$cpu\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "cpu_temperature{cpu=~\"$cpu\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU C-State",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (state) (cpu_idlestate{cpu=~\"$cpu\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "CPU throttling",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "cpu_throttling{cpu=~\"$cpu\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "Interrupts & Context switches",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      { "expr": "interrupts", "legendFormat": "{{kind}} - interrupt" },
      { "expr": "context_switches", "legendFormat": "context switches" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "physical_memory", "legendFormat": "{{kind}}" }
     ]
    },
    {
     "title": "Swap usage",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "swap", "legendFormat": "{{kind}}" }
     ]
    },
    {
     "title": "Memory detailed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      { "expr": "memory_available", "legendFormat": "{{kind}}" },
      { "expr": "memory_committed", "legendFormat": "{{kind}}" },
      { "expr": "memory_transparent_hugepages", "legendFormat": "hugepages-{{kind}}" },
      { "expr": "memory_writeback", "legendFormat": "writeback-{{kind}}" }
     ]
    },
    {
     "title": "Kernel memory allocation",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      { "expr": "memory_kernel", "legendFormat": "{{kind}}" }
     ]
    },
    {
     "title": "Memory slab",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      { "expr": "memory_slab", "legendFormat": "{{kind}}" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "interface_io{interface=~\"$interface\"}",
       "legendFormat": "{{interface}} - {{op}}"
      }
     ]
    },
    {
     "title": "Interface speed",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "interface_speed{interface=~\"$interface\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Interface duplex state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_duplex{interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}} - {{state}}"
      }
     ]
    },
    {
     "title": "Interface operation state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 15, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_operationstate{interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}} - {{state}}"
      }
     ]
    },
    {
     "title": "Interface carrier state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_carrierstate{interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}} - {{state}}"
      }
     ]
    },
    {
     "title": "Interface MTU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "interface_mtu{interface=~\"$interface\"} > 0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network packets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "interface_packets{interface=~\"$interface\"}",
       "legendFormat": "{{interface}} - {{op}}"
      }
     ]
    },
    {
     "title": "Network errors & drops",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "interface_errors{interface=~\"$interface\"}",
       "legendFormat": "error ({{interface}} - {{op}})"
      },
      {
       "expr": "interface_drops{interface=~\"$interface\"}",
       "legendFormat": "drop ({{interface}} - {{op}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Systemd Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "services_cpu{service=~\"$services\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "services_mem{service=~\"$services\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "Kibits" } },
     "targets": [
      {
       "expr": "services_io{service=~\"$services\", op=\"read\"} * -1",
       "legendFormat": "{{service}} - read"
      },
      {
       "expr": "services_io{service=~\"$services\", op=\"write\"}",
       "legendFormat": "{{service}} - write"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "services_iops{service=~\"$services\"}",
       "legendFormat": "{{service}} - {{op}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "processes", "legendFormat": "{{kind}}" }
     ]
    },
    {
     "title": "Process forks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      { "expr": "processes_forks", "legendFormat": "forks" }
     ]
    }
   ]
  },
  {
   "title": "Uptime + NTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "uptime", "legendFormat": "synced" }
     ]
    },
    {
     "title": "NTP synced",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "clock_synced", "legendFormat": "synced" }
     ]
    },
    {
     "title": "NTP offset",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "clock_offset", "legendFormat": "offset" }
     ]
    },
    {
     "title": "NTP error state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "clock_status", "legendFormat": "{{state}}" }
     ]
    }
   ]
  },
  {
   "title": "NFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      { "expr": "nfs_io", "legendFormat": "{{op}}" }
     ]
    },
    {
     "title": "NFS net I/O",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      { "expr": "nfs_net", "legendFormat": "{{op}}" }
     ]
    },
    {
     "title": "NFS threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "nfs_threads", "legendFormat": "threads" }
     ]
    },
    {
     "title": "NFS readcache",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      { "expr": "nfs_readcache", "legendFormat": "{{op}}" }
     ]
    },
    {
     "title": "NFS RPC",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      { "expr": "nfs_rpc", "legendFormat": "{{op}}" }
     ]
    },
    {
     "title": "NFS proc4",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      { "expr": "nfs_proc4", "legendFormat": "{{op}}" }
     ]
    },
    {
     "title": "NFS proc4ops",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      { "expr": "nfs_proc4ops", "legendFormat": "{{op}}" }
     ]
    }
   ]
  },
  {
   "title": "ZFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "ARC Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "zfs_arc_size{op=~\"arcsz|target\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "L2 Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      { "expr": "zfs_l2_size", "legendFormat": "{{op}}" }
     ]
    },
    {
     "title": "ZFS reads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      { "expr": "zfs_reads", "legendFormat": "{{op}}" }
     ]
    },
    {
     "title": "ZFS cache access",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "zfs_hits", "legendFormat": "{{op}}" }
     ]
    },
    {
     "title": "ARC Size Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "zfs_arc_size_breakdown", "legendFormat": "{{op}}" }
     ]
    },
    {
     "title": "ZFS hash elements",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "zfs_hash_elements", "legendFormat": "hashes - {{op}}" }
     ]
    },
    {
     "title": "ZFS important operations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      { "expr": "zfs_important_ops", "legendFormat": "{{op}}" }
     ]
    },
    {
     "title": "ZFS cache hit rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      { "expr": "zfs_hits_rate", "legendFormat": "{{op}}" }
     ]
    }
   ]
  },
  {
   "title": "Disk - $disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "disk_io{disk=~\"$disk\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk I/O Ops - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "abs(disk_io_ops{disk=~\"$disk\"})",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk backlog + busy - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "disk_io_backlog{disk=~\"$disk\"}",
       "legendFormat": "backlog"
      },
      {
       "expr": "disk_busy{disk=~\"$disk\"}",
       "legendFormat": "busy"
      }
     ]
    },
    {
     "title": "Disk utilization - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "disk_utilization{disk=~\"$disk\"}",
       "legendFormat": "utilization"
      }
     ]
    },
    {
     "title": "Disk I/O time - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "abs(disk_iotime{disk=~\"$disk\"})",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk await - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "disk_await{disk=~\"$disk\"}",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk avg I/O size - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "abs(disk_io_size{disk=~\"$disk\"})",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Disk active operations - $disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "disk_qops{disk=~\"$disk\"}",
       "legendFormat": "value"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Space & Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used vs Available - $mountpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "disk_bytes_used{mountpoint=~\"$mountpoint\"}",
       "legendFormat": "{{mountpoint}} used"
      },
      {
       "expr": "disk_bytes_avail{mountpoint=~\"$mountpoint\"}",
       "legendFormat": "{{mountpoint}} available"
      }
     ]
    },
    {
     "title": "Disk Space % Used - $mountpoint",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * disk_bytes_used{mountpoint=~\"$mountpoint\"} / (disk_bytes_used{mountpoint=~\"$mountpoint\"} + disk_bytes_avail{mountpoint=~\"$mountpoint\"})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      { "expr": "disk_temperature", "legendFormat": "{{serial}}" }
     ]
    }
   ]
  }
 ]
}