################################################################
# SSL
################################################################
[[tls.certificates]]
  certFile = "/etc/traefik/certs/cert.pem"
  keyFile = "/etc/traefik/certs/key.pem"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
        certFile = "/etc/traefik/certs/cert.pem"
        keyFile = "/etc/traefik/certs/key.pem"