################################################################
# SSL
################################################################
[entryPoints.websecure]
  address = ":443"
  [entryPoints.websecure.tls]
    certFile = "/etc/traefik/certs/cloudflare.pem"
    keyFile = "/etc/traefik/certs/cloudflare-key.pem"
