################################################################
# Global Configuration
################################################################
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

################################################################
# Entrypoints Configuration
################################################################
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.transport.tls]
      certFile = "/etc/traefik/certs/cert.pem"
      keyFile = "/etc/traefik/certs/key.pem"

################################################################
# Logging Configuration
################################################################
[log]
  level = "INFO"

[accessLog]

################################################################
# API and Dashboard Configuration
################################################################
[api]
  dashboard = true
  insecure = false

################################################################
# Ping Configuration
################################################################
[ping]

################################################################
# HTTP Configuration (Routers & Services)
################################################################
[http]
  [http.routers]
    # Router for Authentik
    [http.routers.authentik]
      rule = "Host(`auth.suskins.co.uk`)"
      service = "authentik"
      entryPoints = ["websecure"]
      tls = true  # No need for certResolver since we're using static certs

  [http.services]
    # Service for Authentik
    [http.services.authentik.loadBalancer]
      [[http.services.authentik.loadBalancer.servers]]
        url = "http://192.168.1.101:9000"