################################################################
# Global Configuration
################################################################
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

################################################################
# Entrypoints Configuration
################################################################
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

################################################################
# Logging Configuration
################################################################
[log]
  level = "INFO"

[accessLog]

################################################################
# API and Dashboard Configuration
################################################################
[api]
  dashboard = true
  insecure = true

################################################################
# Ping Configuration
################################################################
[ping]

################################################################
# Metrics
################################################################
[metrics]
  [metrics.prometheus]

################################################################
# Providers
################################################################
[providers]
  [providers.file]
    directory = "/etc/traefik/dynamic"