################################################################
# Global Configuration
################################################################
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

################################################################
# Entrypoints Configuration
################################################################
[entryPoints]
  [entryPoints.web]
    address = ":80"

    [entryPoints.web.forwardedHeaders]
      trustedIPs = [
        # Cloudflare IPV4's
        "173.245.48.0/20",
        "103.21.244.0/22",
        "103.22.200.0/22",
        "103.31.4.0/22",
        "141.101.64.0/18",
        "108.162.192.0/18",
        "190.93.240.0/20",
        "188.114.96.0/20",
        "197.234.240.0/22",
        "198.41.128.0/17",
        "162.158.0.0/15",
        "104.16.0.0/13",
        "104.24.0.0/14",
        "172.64.0.0/13",
        "131.0.72.0/22",
      ]

  [entryPoints.websecure]
    address = ":443"

################################################################
# Logging Configuration
################################################################
[log]
  level = "INFO"

[accessLog]
  filePath = "/logs/traefik.log"
  format = "json"
  bufferingSize = 0

  [accessLog.filters]
    statusCodes = ["200-299", "400-599"] 

  [accessLog.fields]
    [accessLog.fields.headers]
      defaultMode = "drop"
      [accessLog.fields.headers.names]
        User-Agent = "keep" 

################################################################
# API and Dashboard Configuration
################################################################
[api]
  dashboard = true
  insecure = true

################################################################
# Ping Configuration
################################################################
[ping]

################################################################
# Metrics
################################################################
[metrics]
  [metrics.prometheus]

################################################################
# Providers
################################################################
[providers]
  [providers.file]
    directory = "/etc/traefik/dynamic"
    watch = true
################################################################
# Plugins
################################################################
