---
- name: CLEAN - Perform system cleanup
  hosts: all
  become: true
  become_method: ansible.builtin.su
  vars_files:
    - "{{ lookup('env', 'HOME') }}/.ansible/vault.yml"
  
  tasks:
    - name: Remove unused packages and clear apt cache
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
        clean: true
        purge: true

    - name: Clean journal logs older than 30 days
      ansible.builtin.command: journalctl --vacuum-time=30d

    - name: CLEAN - Prune unused Docker resources
      community.docker.docker_prune:
        containers: false
        images: true
        images_filters:
          dangling: true
        networks: false
        volumes: false
        builder_cache: false

    - name: CLEAN - Reboot server
      ansible.builtin.reboot:
        msg: "Rebooting server after cleanup"
