---
- name: DEPLOY - Deploy containers
  hosts: all
  become: true
  become_method: ansible.builtin.su
  vars_files:
    - "{{ lookup('env', 'HOME') }}/.ansible/vault.yml"

  tasks:
    - name: DEPLOY - Deploy containers
      ansible.builtin.include_tasks:
        file: "../tasks/docker/{{ item }}.yml"
      loop: "{{ containers }}"
