---
- name: DEPLOY - Deploy containers
  hosts: all
  become: true
  become_method: ansible.builtin.su
  vars_files:
    - "~/.ansible/vault.yml"

  tasks:
    - name: DEPLOY - Validate variables
      ansible.builtin.assert:
        that:
          - containers is defined
          - containers | length > 0
        fail_msg: "containers must be defined and not empty"
      tags: [validation]

    - name: DEPLOY - Deploy containers
      block:
        - name: DEPLOY - Include container tasks
          ansible.builtin.include_tasks:
            file: "../tasks/docker/{{ container }}.yml"
          loop: "{{ containers }}"
          loop_control:
            loop_var: container
          register: deploy_results
      rescue:
        - name: DEPLOY - Report deployment failure
          ansible.builtin.fail:
            msg: "Container deployment failed"
      tags: [docker]
