---
- name: SETUP - Setup homeserver
  hosts: all
  become: true
  become_method: ansible.builtin.su
  vars_files:
    - "{{ lookup('env', 'HOME') }}/.ansible/vault.yml"

  tasks:
    - name: SETUP - Update server and install base packages
      ansible.builtin.include_tasks: "../tasks/core/base.yml"

    - name: SETUP - Install docker
      ansible.builtin.include_tasks: "../tasks/core/docker.yml"

    - name: SETUP - Reboot server
      ansible.builtin.reboot:
        msg: "Rebooting server after setup"
