---
- name: SETUP - Setup homeserver
  hosts: all
  become: true
  become_method: ansible.builtin.su
  vars_files:
    - "~/.ansible/vault.yml"

  tasks:
    - name: SETUP - Validate variables
      ansible.builtin.assert:
        that:
          - ansible_os_family is defined
        fail_msg: "ansible_os_family must be defined (run gather_facts)"
      tags: [validation]

  roles:
    - role: common
      tags: [packages]
    - role: docker
      tags: [docker]
    - role: firewall
      when: firewall | default(false) | bool
      tags: [firewall]

  post_tasks:
    - name: SETUP - Deploy core containers
      ansible.builtin.include_role:
        name: container
      vars: "{{ core_container_definitions[item] }}"
      loop: "{{ core_containers | default([]) }}"
      tags: [docker, core]

    - name: SETUP - Reboot server
      ansible.builtin.reboot:
        msg: "Rebooting server after setup"
      when: reboot_required | default(false)
      tags: [reboot]
