---
- name: UPDATE - Update and upgrade host
  hosts: all
  become: true
  become_method: ansible.builtin.su
  become_user: root
  vars_files:
    - ../vault.yml

  tasks:
    - name: UPDATE - Update packages with apt
      ansible.builtin.apt:
        update_cache: true

    - name: UPDATE - Upgrade packages with apt
      ansible.builtin.apt:
        upgrade: dist

    - name: UPDATE - Update Docker Containers
      ansible.builtin.include_tasks: "../tasks/docker/{{ item }}.yml"
      with_items:
        - "{{ containers }}"

    - name: UPDATE - Update Core Docker Containers
      ansible.builtin.include_tasks: "../tasks/docker/{{ item }}.yml"
      with_items:
        - "{{ core_containers }}"

    - name: SETUP - Reboot server
      ansible.builtin.reboot:
        msg: "Rebooting server after setup"
