---
- name: UPDATE - Update and upgrade host
  hosts: all
  become: true
  become_method: ansible.builtin.su
  vars_files:
    - ../vault.yml

  tasks:
    - name: UPDATE - Update packages
      ansible.builtin.apt:
        update_cache: true

    - name: UPDATE - Upgrade packages
      ansible.builtin.apt:
        upgrade: dist

    - name: UPDATE - Update Docker Containers
      ansible.builtin.include_tasks:
        file: "../tasks/docker/{{ item }}.yml"
      loop: "{{ containers }}"

    - name: UPDATE - Update Core Docker Containers
      ansible.builtin.include_tasks:
        file: "../tasks/docker/{{ item }}.yml"
      loop: "{{ core_containers }}"

    - name: SETUP - Reboot server
      ansible.builtin.reboot:
        msg: "Rebooting server after setup"
