---
- name: UPDATE - Update and upgrade host
  hosts: all
  become: true
  become_method: ansible.builtin.su
  vars_files:
    - "~/.ansible/vault.yml"

  tasks:
    - name: UPDATE - Validate variables
      ansible.builtin.assert:
        that:
          - containers is defined
          - core_containers is defined
        fail_msg: "containers and core_containers must be defined"
      tags: [validation]

    - name: UPDATE - Update packages
      ansible.builtin.apt:
        update_cache: true
      register: apt_update_res
      tags: [packages]

    - name: UPDATE - Upgrade packages
      ansible.builtin.apt:
        upgrade: dist
      register: apt_upgrade_res
      tags: [packages]

    - name: UPDATE - Update firewall
      ansible.builtin.include_tasks:
        file: "../tasks/other/firewall.yml"
      register: firewall_results
      when: firewall | default(false) | bool
      tags: [firewall]

    - name: UPDATE - Docker operations
      block:
        - name: UPDATE - Build expected container list
          ansible.builtin.set_fact:
            expected_containers: "{{ (containers | default([])) + (core_containers | default([])) + (special_containers | default([])) }}"

        - name: UPDATE - Update Core Docker Containers
          ansible.builtin.include_tasks:
            file: "../tasks/docker/{{ container }}.yml"
          loop: "{{ core_containers | default([]) }}"
          loop_control:
            loop_var: container
          register: core_results

        - name: UPDATE - Update Docker Containers
          ansible.builtin.include_tasks:
            file: "../tasks/docker/{{ container }}.yml"
          loop: "{{ containers | default([]) }}"
          loop_control:
            loop_var: container
          register: containers_results

        - name: UPDATE - Update Special Containers
          ansible.builtin.include_tasks:
            file: "../tasks/docker/{{ container }}.yml"
          loop: "{{ special_containers | default([]) }}"
          loop_control:
            loop_var: container
          register: special_results

        - name: UPDATE - Get all containers
          community.docker.docker_host_info:
            containers: true
          register: all_containers

        - name: UPDATE - Remove containers no longer defined
          community.docker.docker_container:
            name: "{{ item.Names[0] | regex_replace('^/', '') }}"
            state: absent
          loop: "{{ all_containers.containers | default([]) }}"
          loop_control:
            label: "{{ item.Names[0] | default('unknown') }}"
          when: (item.Names[0] | regex_replace('^/', '')) not in expected_containers
          register: remove_results
      rescue:
        - name: UPDATE - Report docker failure
          ansible.builtin.fail:
            msg: "Docker operations failed"
      tags: [docker]

    - name: UPDATE - Aggregate services from all hosts
      ansible.builtin.include_tasks:
        file: "../tasks/core/aggregate_services.yml"
      run_once: true
      tags: [services]

    - name: UPDATE - Update Cloudflare DNS records
      ansible.builtin.include_tasks:
        file: "../tasks/other/cloudflare_cnames.yml"
      run_once: true
      tags: [dns]

    - name: UPDATE - Generate README
      ansible.builtin.include_tasks:
        file: "../tasks/other/generate_readme.yml"
      run_once: true
      tags: [docs]

    - name: UPDATE - Set reboot_required if important tasks changed
      ansible.builtin.set_fact:
        reboot_required: true
      when: >
        (apt_update_res.changed | default(false)) or
        (apt_upgrade_res.changed | default(false)) or
        (firewall_results.changed | default(false)) or
        (core_results.changed | default(false)) or
        (containers_results.changed | default(false)) or
        (special_results.changed | default(false)) or
        (remove_results.changed | default(false))
      tags: [reboot]

    - name: UPDATE - Reboot server
      ansible.builtin.reboot:
        msg: "Rebooting server after update"
      when: reboot_required | default(false)
      tags: [reboot]
