---
- name: UPDATE - Update and upgrade host
  hosts: all
  become: true
  become_method: ansible.builtin.su
  vars_files:
    - "~/.ansible/vault.yml"

  tasks:
    - name: UPDATE - Validate variables
      ansible.builtin.assert:
        that:
          - containers is defined
          - core_containers is defined
        fail_msg: "containers and core_containers must be defined"
      tags: [validation]

    - name: UPDATE - Update packages
      ansible.builtin.apt:
        update_cache: true
      register: apt_update_res
      tags: [packages]

    - name: UPDATE - Upgrade packages
      ansible.builtin.apt:
        upgrade: dist
      register: apt_upgrade_res
      tags: [packages]

    - name: UPDATE - Update firewall
      ansible.builtin.include_tasks:
        file: "../tasks/other/firewall.yml"
      register: firewall_results
      when: firewall | default(false) | bool
      tags: [firewall]

    - name: UPDATE - Docker operations
      block:
        - name: UPDATE - Gather Docker container facts
          ansible.builtin.command: docker ps -a --format '{% raw %}{{ .Names }}{% endraw %}'
          register: docker_containers

        - name: UPDATE - Stop all running containers
          community.docker.docker_container:
            name: "{{ item }}"
            state: stopped
          loop: "{{ docker_containers.stdout_lines | default([]) }}"
          when: docker_containers.stdout_lines is defined and docker_containers.stdout_lines | length > 0
          register: stop_results

        - name: UPDATE - Update Core Docker Containers
          ansible.builtin.include_tasks:
            file: "../tasks/docker/{{ item }}.yml"
          loop: "{{ core_containers | default([]) }}"
          register: core_results

        - name: UPDATE - Update Docker Containers
          ansible.builtin.include_tasks:
            file: "../tasks/docker/{{ item }}.yml"
          loop: "{{ containers | default([]) }}"
          register: containers_results

        - name: UPDATE - Update Special Containers
          ansible.builtin.include_tasks:
            file: "../tasks/docker/{{ item }}.yml"
          loop: "{{ special_containers | default([]) }}"
          register: special_results

        - name: UPDATE - Remove stopped containers not wanted
          community.docker.docker_container:
            name: "{{ item }}"
            state: absent
          loop: "{{ docker_containers.stdout_lines | default([]) }}"
          when: item not in (containers | default([]) + core_containers | default([]) + special_containers | default([]))
          register: remove_results
      rescue:
        - name: UPDATE - Report docker failure
          ansible.builtin.fail:
            msg: "Docker operations failed"
      tags: [docker]

    - name: UPDATE - Set reboot_required if important tasks changed
      ansible.builtin.set_fact:
        reboot_required: true
      when: >
        (apt_update_res.changed | default(false)) or
        (apt_upgrade_res.changed | default(false)) or
        (firewall_results.changed | default(false)) or
        (stop_results.changed | default(false)) or
        (core_results.changed | default(false)) or
        (containers_results.changed | default(false)) or
        (special_results.changed | default(false)) or
        (remove_results.changed | default(false))
      tags: [reboot]

    - name: UPDATE - Reboot server
      ansible.builtin.reboot:
        msg: "Rebooting server after update"
      when: reboot_required | default(false)
      tags: [reboot]
