---
- name: UPDATE - Update and upgrade host
  hosts: all
  become: true
  become_method: ansible.builtin.su
  vars_files:
    - "~/.ansible/vault.yml"

  tasks:
    - name: UPDATE - Validate variables
      ansible.builtin.assert:
        that:
          - containers is defined
          - core_containers is defined
        fail_msg: "containers and core_containers must be defined"
      tags: [validation]

    - name: UPDATE - Update packages
      ansible.builtin.apt:
        update_cache: true
      register: apt_update_res
      tags: [packages]

    - name: UPDATE - Upgrade packages
      ansible.builtin.apt:
        upgrade: dist
      register: apt_upgrade_res
      tags: [packages]

    - name: UPDATE - Update firewall
      ansible.builtin.include_role:
        name: firewall
      when: firewall | default(false) | bool
      tags: [firewall]

    - name: UPDATE - Docker operations
      block:
        - name: UPDATE - Build expected container list
          ansible.builtin.set_fact:
            expected_containers: "{{ (containers | default([])) + (core_containers | default([])) + (special_containers | default([])) }}"

        - name: UPDATE - Update core containers
          ansible.builtin.include_role:
            name: container
          vars: "{{ core_container_definitions[item] }}"
          loop: "{{ core_containers | default([]) }}"

        - name: UPDATE - Update regular containers
          ansible.builtin.include_role:
            name: container
          vars: "{{ container_definitions[item] }}"
          loop: "{{ containers | default([]) }}"

        - name: UPDATE - Get all containers
          community.docker.docker_host_info:
            containers: true
          register: all_containers

        - name: UPDATE - Remove containers no longer defined
          community.docker.docker_container:
            name: "{{ item.Names[0] | regex_replace('^/', '') }}"
            state: absent
          loop: "{{ all_containers.containers | default([]) }}"
          loop_control:
            label: "{{ item.Names[0] | default('unknown') }}"
          when: (item.Names[0] | regex_replace('^/', '')) not in expected_containers
      tags: [docker]

- name: UPDATE - Deploy special containers
  hosts: all
  become: true
  become_method: ansible.builtin.su
  vars_files:
    - "~/.ansible/vault.yml"

  tasks:
    - name: UPDATE - Deploy Traefik
      ansible.builtin.include_role:
        name: traefik
      when: "'traefik' in (special_containers | default([]))"
      tags: [docker, special]

    - name: UPDATE - Deploy Prometheus
      ansible.builtin.include_role:
        name: prometheus
      when: "'prometheus' in (special_containers | default([]))"
      tags: [docker, special]

    - name: UPDATE - Deploy Gatus
      ansible.builtin.include_role:
        name: gatus
      when: "'gatus' in (special_containers | default([]))"
      tags: [docker, special]

    - name: UPDATE - Deploy Homepage
      ansible.builtin.include_role:
        name: homepage
      when: "'homepage' in (special_containers | default([]))"
      tags: [docker, special]

    - name: UPDATE - Update Cloudflare DNS records
      ansible.builtin.include_role:
        name: cloudflare_dns
      run_once: true
      tags: [dns]

    - name: UPDATE - Reboot server if needed
      ansible.builtin.reboot:
        msg: "Rebooting server after update"
      when: reboot_required | default(false)
      tags: [reboot]
