################################################################
# HTTP Configuration (Routers & Services)
################################################################
[http]
  [http.routers]
    [http.routers.authentik]
      rule = "Host(`auth.suskins.co.uk`)"
      service = "authentik"
      entryPoints = ["websecure"]
      middlewares = ["crowdsec"]
      tls = true
    [http.routers.home]
      rule = "Host(`home.suskins.co.uk`)"
      service = "home"
      entryPoints = ["websecure"]
      middlewares = ["crowdsec", "authentik"]
      tls = true

    # Pubgolf Routers
    [http.routers.pubgolf]
      rule = "Host(`pubgolf.suskins.co.uk`)"
      service = "pubgolf"
      entryPoints = ["websecure"]
      middlewares = ["crowdsec"]
      tls = true      
    [http.routers.pubgolfapi]
      rule = "Host(`api.suskins.co.uk`)"
      service = "pubgolfapi"
      entryPoints = ["websecure"]
      middlewares = ["crowdsec"]
      tls = true            
    [http.routers.pubgolfme]
      rule = "Host(`pubgolf.me`)"
      service = "pubgolf"
      entryPoints = ["websecure"]
      middlewares = ["crowdsec"]
      tls = true
    [http.routers.pubgolfapi-me]
      rule = "Host(`api.pubgolf.me`)"
      service = "pubgolfapi"
      entryPoints = ["websecure"]
      middlewares = ["crowdsec"]
      tls = true

  [http.services]
    [http.services.authentik.loadBalancer]
      [[http.services.authentik.loadBalancer.servers]]
        url = "http://192.168.0.105:9000"
    [http.services.home.loadBalancer]
      [[http.services.home.loadBalancer.servers]]
        url = "http://192.168.0.102:3000"
    [http.services.pubgolf.loadBalancer]
      [[http.services.pubgolf.loadBalancer.servers]]
        url = "http://192.168.0.102:3003"    
    [http.services.pubgolfapi.loadBalancer]
      [[http.services.pubgolfapi.loadBalancer.servers]]
        url = "http://192.168.0.102:8080"              
        