[http]  
  [http.middlewares]
    [http.middlewares.crowdsec]
      [http.middlewares.crowdsec.plugin]
        [http.middlewares.crowdsec.plugin.bouncer]
        enabled = true
        defaultDecisionSeconds = 60
        crowdsecMode = "live"
        crowdsecAppsecEnabled = false
        crowdsecAppsecHost = "crowdsec:7422"
        crowdsecAppsecFailureBlock = true
        crowdsecAppsecUnreachableBlock = true
        crowdsecLapiKey = "TODO"
        crowdsecLapiHost = "crowdsec:8080"
        crowdsecLapiScheme = "http"
        crowdsecLapiTLSInsecureVerify = false
        
        forwardedHeadersTrustedIPs = [
          "10.0.0.0/8",
          "172.16.0.0/12",
          "192.168.0.0/16"
        ]
        
        clientTrustedIPs = [
          "10.0.0.0/8",
          "172.16.0.0/12",
          "192.168.0.0/16"
        ]
