---
username: mediaserver
puid: 1000
pgid: 1000
base_dir: /home/mediaserver/server-mediaserver
nas_ip: 192.168.0.100
mount_nas: true

containers:
  - plex
  - sonarr
  - radarr
  - overseerr
  - prowlarr
  - bazarr
  - gluetun
  - metube
  - qbittorrent
  - doplarr
  - open_books
