---
- name: BYTE_STASH - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  loop:
    - "{{ base_dir }}/byte_stash"

- name: BYTE_STASH - Create container
  community.docker.docker_container:
    name: byte_stash
    image: ghcr.io/jordan-dalby/bytestash:1.5.8
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "5000:5000"
    volumes:
      - "{{ base_dir }}/byte_stash:/data/snippets"
    env:
      BASE_PATH: ""
      JWT_SECRET: "{{ BYTE_STASH_JWT_SECRET }}"
      TOKEN_EXPIRY: 24h
      ALLOW_NEW_ACCOUNTS: "true"
      DEBUG: "false"
      DISABLE_ACCOUNTS: "false"
      DISABLE_INTERNAL_ACCOUNTS: "true"
      OIDC_ENABLED: "true"
      OIDC_DISPLAY_NAME: "Authentik"
      OIDC_ISSUER_URL: "https://authentik.suskins.co.uk/application/o/bytestash/"
      OIDC_CLIENT_ID: "{{ BYTE_STASH_OIDC_CLIENT_ID }}"
      OIDC_CLIENT_SECRET: "{{ BYTE_STASH_OIDC_CLIENT_SECRET}}"
      OIDC_SCOPES: "openid profile email"

- name: BYTE_STASH - Set homepage entry
  set_fact:
    homepage_entry: "{{ (homepage_entry | default([])) + [ {
      'container': 'bytestash',
      'ip': inventory_hostname,
      'friendly_name': friendly_name,
      'port': 5000,
    } ] }}"
