---
- name: CALIBRE WEB AUTOMATED - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  loop:
    - "{{ base_dir }}/calibre-web-automated"

- name: CALIBRE WEB AUTOMATED - Create container
  community.docker.docker_container:
    name: calibre-web-automated
    image: crocodilestick/calibre-web-automated:v4.0.6
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "8083:8083"
    volumes:
      - "{{ base_dir }}/calibre-web-automated:/config"
      - "/mnt/media/books/data:/cwa-book-ingest"
      - "/mnt/media/books/library:/calibre-library"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ puid | string }}"
      PGID: "{{ pgid | string }}"

- name: CALIBRE WEB AUTOMATED - Define service entry
  ansible.builtin.set_fact:
    calibre_web_automated_entry:
      name: calibre-web-automated
      description: eBook library
      icon: calibre-web
      host: "calibre.{{ domain }}"
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 8083
      scheme: http
      secured: false
      healthcheck: true
      homepage: true
      proxied: true

- name: CALIBRE WEB AUTOMATED - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services + [calibre_web_automated_entry] }}"
