---
- name: CROWDSEC - Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0777"
  loop:
    - "{{ base_dir }}/crowdsec/config"
    - "{{ base_dir }}/crowdsec/data"
    - "{{ base_dir }}/crowdsec/logs"

- name: CROWDSEC - Deploy container
  community.docker.docker_container:
    name: crowdsec
    image: crowdsecurity/crowdsec
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab  
    ports:
      - "7422:7422"
      - "6060:6060"
      - "9876:8080"
    env:
      COLLECTIONS="crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/sshd crowdsecurity/linux crowdsecurity/appsec-generic-rules crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-crs"
      GID="{{ pgid }}" 
    volumes:
      - "{{ base_dir }}/crowdsec/data:/var/lib/crowdsec/data"
      - "{{ base_dir }}/crowdsec/config:/etc/crowdsec"
      - "{{ base_dir }}/traefik/logs:/var/log/traefik:ro"
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog:ro      

- name: CROWDSEC - Add to scrape configs
  set_fact:
    prometheus_scrape_configs: >-
      {{
        (prometheus_scrape_configs | default([])) +
        [ {
          'job_name': 'crowdsec',
          'scrape_interval': '60s',
          'static_configs': [ { 'targets': [ ansible_host ~ ':6060' ] } ]
        } ]
      }}      