---
- name: GHOST - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0777"
  loop:
    - "{{ base_dir }}/ghost"
    - "{{ base_dir }}/ghost-db"

- name: GHOST - Create container
  community.docker.docker_container:
    name: ghost
    image: ghost
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - 2368:2368
    volumes:
      - "{{ base_dir }}/ghost:/var/lib/ghost/content"
    env:
      #NODE_ENV=development
      url=https://blog.suskins.co.uk
      database__client=mysql
      database__connection__host=ghost-db
      database__connection__user=root
      database__connection__password={{ ghost_db_password }}
      database__connection__database=ghost

- name: GHOST-DB - Create container
  community.docker.docker_container:
    name: ghost-db
    image: mysql:8.0
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    volumes:
      - "{{ base_dir }}/ghost-db:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD={{ ghost_db_password }}
