---
- name: GRAPHITE-EXPORTER - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0777"
  loop:
    - "{{ base_dir }}/graphite-exporter"

- name: GRAPHITE-EXPORTER - Create config
  ansible.builtin.copy:
    # Mapping adapted from https://github.com/Supporterino/truenas-graphite-to-prometheus
    # for TrueNAS SCALE's netdata-based Graphite export (replaces the old TrueNAS CORE /
    # collectd-based mapping, which no longer matches SCALE's metric paths).
    # Requires the TrueNAS reporting exporter's "Prefix" field to be set to "truenas".
    content: |
      mappings:
      ################################################
      # memory mapping
      ################################################

      - match: 'truenas\.(.*)\.system\.ram\.(.*)'
        match_type: "regex"
        name: "physical_memory"
        labels:
          kind: "${2}"

      - match: 'truenas\.(.*)\.mem\.(.*)\.(.*)'
        match_type: "regex"
        name: "memory_${2}"
        labels:
          kind: "${3}"

      - match: 'truenas\.(.*)\.system\.swap\.(.*)'
        match_type: "regex"
        name: "swap"
        labels:
          kind: "${2}"

      ################################################
      # service mapping
      ################################################

      - match: 'truenas\.(.*)\.services\.cpu\.(.*)'
        match_type: "regex"
        name: "services_cpu"
        labels:
          service: "${2}"

      - match: 'truenas\.(.*)\.services\.io_ops_read\.(.*)'
        match_type: "regex"
        name: "services_iops"
        labels:
          op: "read"
          service: "${2}"

      - match: 'truenas\.(.*)\.services\.io_ops_write\.(.*)'
        match_type: "regex"
        name: "services_iops"
        labels:
          op: "write"
          service: "${2}"

      - match: 'truenas\.(.*)\.services\.io_read\.(.*)'
        match_type: "regex"
        name: "services_io"
        labels:
          op: "read"
          service: "${2}"

      - match: 'truenas\.(.*)\.services\.io_write\.(.*)'
        match_type: "regex"
        name: "services_io"
        labels:
          op: "write"
          service: "${2}"

      - match: 'truenas\.(.*)\.services\.mem_usage\.(.*)'
        match_type: "regex"
        name: "services_mem"
        labels:
          service: "${2}"

      ################################################
      # disk smart metrics
      ################################################

      - match: 'truenas\.(.*)\.smart\.log\.smart\.disktemp\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_temperature"
        labels:
          serial: "${2}"

      - match: 'truenas\.(.*)\.smart_log_smart\.disktemp\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_temperature"
        labels:
          serial: "${2}"

      ################################################
      # disk operation mappings
      ################################################

      - match: 'truenas\.(.*)\.disk\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_io"
        labels:
          disk: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.disk_ops\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_io_ops"
        labels:
          disk: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.disk_ext\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_io"
        labels:
          disk: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.disk_ext_ops\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_io_ops"
        labels:
          disk: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.disk_backlog\.(.*)\.backlog'
        match_type: "regex"
        name: "disk_io_backlog"
        labels:
          disk: "${2}"

      - match: 'truenas\.(.*)\.disk_busy\.(.*)\.busy'
        match_type: "regex"
        name: "disk_busy"
        labels:
          disk: "${2}"

      - match: 'truenas\.(.*)\.disk_util\.(.*)\.utilization'
        match_type: "regex"
        name: "disk_utilization"
        labels:
          disk: "${2}"

      - match: 'truenas\.(.*)\.disk_mops\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_io"
        labels:
          disk: "${2}"
          op: "merged_${3}"

      - match: 'truenas\.(.*)\.disk_ext_mops\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_io"
        labels:
          disk: "${2}"
          op: "merged_${3}"

      - match: 'truenas\.(.*)\.disk_iotime\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_iotime"
        labels:
          disk: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.disk_ext_iotime\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_iotime"
        labels:
          disk: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.disk_qops\.(.*)\.operations'
        match_type: "regex"
        name: "disk_qops"
        labels:
          disk: "${2}"

      - match: 'truenas\.(.*)\.disk_await\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_await"
        labels:
          disk: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.disk_ext_await\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_await"
        labels:
          disk: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.disk_avgsz\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_io_size"
        labels:
          disk: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.disk_ext_avgsz\.(.*)\.(.*)'
        match_type: "regex"
        name: "disk_io_size"
        labels:
          disk: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.disk_svctm\.(.*)\.svctm'
        match_type: "regex"
        name: "disk_svctm"
        labels:
          disk: "${2}"

      - match: 'truenas\.(.*)\.system\.io\.(.*)'
        match_type: "regex"
        name: "system_io"
        labels:
          op: "${2}"

      ################################################
      # CPU mapping
      ################################################

      - match: 'truenas\.(.*)\.system\.intr\.interrupts'
        match_type: "regex"
        name: "interrupts"
        labels:
          kind: "hard"

      - match: 'truenas\.(.*)\.system\.cpu\.softirq'
        match_type: "regex"
        name: "interrupts"
        labels:
          kind: "soft"

      - match: 'truenas\.(.*)\.cpu\.(.*)\.softirq'
        match_type: "regex"
        name: "cpu_softirq"
        labels:
          cpu: "${2}"

      - match: 'truenas\.(.*)\.system\.ctxt\.switches'
        match_type: "regex"
        name: "context_switches"

      - match: 'truenas\.(.*)\.system\.cpu\.(.*)'
        match_type: "regex"
        name: "cpu_total"
        labels:
          kind: "${2}"

      - match: 'truenas\.(.*)\.cputemp\.temperatures\.(.*)'
        match_type: "regex"
        name: "cpu_temperature"
        labels:
          cpu: "${2}"

      - match: 'truenas\.(.*)\.cpu\.core_throttling\.(.*)'
        match_type: "regex"
        name: "cpu_throttling"
        labels:
          cpu: "${2}"

      - match: 'truenas\.(.*)\.cpu\.cpufreq\.(.*)'
        match_type: "regex"
        name: "cpu_frequency"
        labels:
          cpu: "${2}"

      - match: 'truenas\.(.*)\.cpu\.(.*)_cpuidle\.(.*)'
        match_type: "regex"
        name: "cpu_idlestate"
        labels:
          cpu: "${2}"
          state: "${3}"

      - match: 'truenas\.(.*)\.cpu\.(.*)\.(.*)'
        match_type: "regex"
        name: "cpu_usage"
        labels:
          cpu: "${2}"
          kind: "${3}"

      ################################################
      # process mapping
      ################################################

      - match: 'truenas\.(.*)\.system\.forks\.started'
        match_type: "regex"
        name: "processes_forks"

      - match: 'truenas\.(.*)\.system\.processes\.(.*)'
        match_type: "regex"
        name: "processes"
        labels:
          kind: "${2}"

      - match: 'truenas\.(.*)\.system\.active_processes\.(.*)'
        match_type: "regex"
        name: "processes"
        labels:
          kind: "${2}"

      ################################################
      # uptime mapping
      ################################################

      - match: 'truenas\.(.*)\.system\.uptime\.uptime'
        match_type: "regex"
        name: "uptime"

      - match: 'truenas\.(.*)\.system\.clock_sync_state\.state'
        match_type: "regex"
        name: "clock_synced"

      - match: 'truenas\.(.*)\.system\.clock_status\.(.*)'
        match_type: "regex"
        name: "clock_status"
        labels:
          state: "${2}"

      - match: 'truenas\.(.*)\.system\.clock_sync_offset\.offset'
        match_type: "regex"
        name: "clock_offset"

      ################################################
      # load mapping
      ################################################

      - match: 'truenas\.(.*)\.system\.load\.(.*)'
        match_type: "regex"
        name: "system_load"
        labels:
          kind: "${2}"

      ################################################
      # nsfd mappings
      ################################################

      - match: 'truenas\.(.*)\.nfsd\.(.*)\.(.*)'
        match_type: "regex"
        name: "nfs_${2}"
        labels:
          op: "${3}"

      ################################################
      # zfs mappings
      ################################################

      - match: 'truenas\.(.*)\.zfs\.(.*)\.(.*)'
        match_type: "regex"
        name: "zfs_${2}"
        labels:
          op: "${3}"

      - match: 'truenas\.(.*)\.zfspool\.state_(.*)\.(.*)'
        match_type: "regex"
        name: "zfs_pool"
        labels:
          pool: "${2}"
          state: "${3}"

      ################################################
      # network mappings
      ################################################

      - match: 'truenas\.(.*)\.net\.(.*)\.(.*)'
        match_type: "regex"
        name: "interface_io"
        labels:
          interface: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.net_speed\.(.*)\.speed'
        match_type: "regex"
        name: "interface_speed"
        labels:
          interface: "${2}"

      - match: 'truenas\.(.*)\.net_duplex\.(.*)\.(.*)'
        match_type: "regex"
        name: "interface_duplex"
        labels:
          interface: "${2}"
          state: "${3}"

      - match: 'truenas\.(.*)\.net_operstate\.(.*)\.(.*)'
        match_type: "regex"
        name: "interface_operationstate"
        labels:
          interface: "${2}"
          state: "${3}"

      - match: 'truenas\.(.*)\.net_carrier\.(.*)\.(.*)'
        match_type: "regex"
        name: "interface_carrierstate"
        labels:
          interface: "${2}"
          state: "${3}"

      - match: 'truenas\.(.*)\.net_mtu\.(.*)\.mtu'
        match_type: "regex"
        name: "interface_mtu"
        labels:
          interface: "${2}"

      - match: 'truenas\.(.*)\.net_packets\.(.*)\.(.*)'
        match_type: "regex"
        name: "interface_packets"
        labels:
          interface: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.net_errors\.(.*)\.(.*)'
        match_type: "regex"
        name: "interface_errors"
        labels:
          interface: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.net_drops\.(.*)\.(.*)'
        match_type: "regex"
        name: "interface_drops"
        labels:
          interface: "${2}"
          op: "${3}"

      - match: 'truenas\.(.*)\.system\.net\.(.*)'
        match_type: "regex"
        name: "system_net_io"
        labels:
          op: "${2}"

      ################################################
      # arcstat mapping
      ################################################

      - match: 'truenas\.(.*)\.truenas_arcstats\.(.*)\.(.*)'
        match_type: "regex"
        name: "truenas_arcstats"
        labels:
          type: "${2}"
          subtype: "${3}"

      - match: 'truenas\.(.*)\.truenas_meminfo\.(.*)\.(.*)'
        match_type: "regex"
        name: "truenas_meminfo"
        labels:
          kind: "${2}"

      ################################################
      # disk by ID mapping
      ################################################

      - match: 'truenas\.(.*)\.truenas_disk_stats\.(.*)\.(reads|writes)'
        match_type: "regex"
        name: "disk_io"
        labels:
          disk: "${2}"
          op: "${3}"
          unit: "KiB/s"

      - match: 'truenas\.(.*)\.truenas_disk_stats\.ops\.(.*)\.(read_ops|write_ops)'
        match_type: "regex"
        name: "disk_io_ops"
        labels:
          disk: "${2}"
          op: "${3}"
          unit: "op/s"

      - match: 'truenas\.(.*)\.truenas_disk_stats\.busy\.(.*)\.busy'
        match_type: "regex"
        name: "disk_busy"
        labels:
          disk: "${2}"
          unit: "ms"

      ################################################
      # disk space and inodes
      ################################################

      - match: 'truenas\.(.*)\.disk_space\.(.*)\.used'
        match_type: "regex"
        name: "disk_bytes_used"
        labels:
          mountpoint: "${2}"
          unit: "GiB"

      - match: 'truenas\.(.*)\.disk_space\.(.*)\.avail'
        match_type: "regex"
        name: "disk_bytes_avail"
        labels:
          mountpoint: "${2}"
          unit: "GiB"

      - match: 'truenas\.(.*)\.disk_space\.(.*)\.reserved_for_root'
        match_type: "regex"
        name: "disk_bytes_reserved_for_root"
        labels:
          mountpoint: "${2}"
          unit: "GiB"

      - match: 'truenas\.(.*)\.disk_inodes\.(.*)\.used'
        match_type: "regex"
        name: "disk_inodes_used"
        labels:
          mountpoint: "${2}"
          unit: "inodes"

      - match: 'truenas\.(.*)\.disk_inodes\.(.*)\.avail'
        match_type: "regex"
        name: "disk_inodes_avail"
        labels:
          mountpoint: "${2}"
          unit: "inodes"

      - match: 'truenas\.(.*)\.disk_inodes\.(.*)\.reserved_for_root'
        match_type: "regex"
        name: "disk_inodes_reserved_for_root"
        labels:
          mountpoint: "${2}"
          unit: "inodes"
    dest: "{{ base_dir }}/graphite-exporter/graphite_mapping.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
  register: graphite_exporter_config

- name: GRAPHITE-EXPORTER - Pre-pull image
  community.docker.docker_image:
    name: "{{ image }}"
    source: pull
    force_source: true
  vars:
    image: prom/graphite-exporter:v0.17.0

- name: GRAPHITE-EXPORTER - Create container
  community.docker.docker_container:
    name: graphite-exporter
    image: prom/graphite-exporter:v0.17.0
    restart_policy: always
    state: started
    pull: false
    networks:
      - name: homelab
    ports:
      - "9108:9108"
      - "2003:9109"
      - "2003:9109/udp"
    volumes:
      - "{{ base_dir }}/graphite-exporter/graphite_mapping.conf:/tmp/graphite_mapping.conf"
    command: --graphite.mapping-config=/tmp/graphite_mapping.conf

- name: GRAPHITE-EXPORTER - Restart to apply config changes
  ansible.builtin.command: docker restart graphite-exporter
  when: graphite_exporter_config.changed
  changed_when: true

- name: GRAPHITE-EXPORTER - Define service entry
  ansible.builtin.set_fact:
    graphite_exporter_entry:
      name: graphite-exporter
      host: "graphite-exporter.{{ domain }}"
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 9108
      scheme: http
      secured: false
      healthcheck: true
      metrics: true
      metrics_port: 9108

- name: GRAPHITE-EXPORTER - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services + [graphite_exporter_entry] }}"
