---
- name: HARNESS - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0777"
  loop:
    - "{{ base_dir }}/harness"

- name: HARNESS - Create container
  community.docker.docker_container:
    name: harness
    image: harness/harness
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - '3000:3000'
      - '3022:3022'
    volumes:
      - "{{ base_dir }}/harness:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      GITNESS_URL_BASE=http://192.168.0.105:3000
      GITNESS_PRINCIPAL_ADMIN_EMAIL={{ HARNESS_USERNAME }}
      GITNESS_PRINCIPAL_ADMIN_PASSWORD={{ HARNESS_PASSWORD }}
      GITNESS_USER_SIGNUP_ENABLED=false
      PUID={{ puid }}
      PGID={{ pgid }}
      TZ={{ timezone }}
