---
- name: LINKWARDEN - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0777"
  loop:
    - "{{ base_dir }}/linkwarden"

- name: LINKWARDEN - Create Container
  community.docker.docker_container:
    name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "84:3000"
    volumes:
      - "{{ base_dir }}/linkwarden/data:/data/data"
    env:
      DATABASE_URL: "postgresql://postgres:CUSTOM_POSTGRES_PASSWORD@postgres:5432/postgres"
      NEXTAUTH_SECRET: "VERY_SENSITIVE_SECRET"
      NEXTAUTH_URL: "http://localhost:84/api/v1/auth"
