---
- name: MAGIC-MIRROR - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  loop:
    - "{{ base_dir }}/magic-mirror"
    - "{{ base_dir }}/magic-mirror/config"
    - "{{ base_dir }}/magic-mirror/modules"
    - "{{ base_dir }}/magic-mirror/css"

- name: MAGIC-MIRROR - Create container
  community.docker.docker_container:
    name: magic-mirror
    image: karsten13/magicmirror:v2.33.0
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    volumes:
      - "{{ base_dir }}/magic-mirror/config:/opt/magic_mirror/config"
      - "{{ base_dir }}/magic-mirror/modules:/opt/magic_mirror/modules"
      - "{{ base_dir }}/magic-mirror/css:/opt/magic_mirror/css"
    ports:
      - "9926:8080"

- name: MAGIC-MIRROR - Define service entry
  ansible.builtin.set_fact:
    magic_mirror_entry:
      container: magicmirror
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 9926

- name: MAGIC-MIRROR - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ (docker_services | default([])) + [magic_mirror_entry] }}"
