---
- name: MARGINALIA-WORKER-METADATA - Create container
  community.docker.docker_container:
    name: marginalia-worker-metadata
    image: ghcr.io/bensuskins/marginalia-worker-metadata:latest
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    env:
      DATABASE_URL: "postgres://marginalia:{{ MARGINALIA_POSTGRES_PASSWORD }}@marginalia-postgres:5432/marginalia?sslmode=disable"
      SECRET_ENCRYPTION_KEY: "{{ MARGINALIA_SECRET_ENCRYPTION_KEY }}"
