---
- name: MARGINALIA-POSTGRES - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "999"
    group: "999"
    mode: "0750"
  loop:
    - "{{ base_dir }}/marginalia/postgres"

- name: MARGINALIA-POSTGRES - Create container
  community.docker.docker_container:
    name: marginalia-postgres
    image: postgres:16-alpine
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    volumes:
      - "{{ base_dir }}/marginalia/postgres:/var/lib/postgresql/data"
    env:
      POSTGRES_DB: marginalia
      POSTGRES_USER: marginalia
      POSTGRES_PASSWORD: "{{ MARGINALIA_POSTGRES_PASSWORD }}"

