---
- name: MARGINALIA-WORKER-REVIEWS - Create container
  community.docker.docker_container:
    name: marginalia-worker-reviews
    image: ghcr.io/bensuskins/marginalia-worker-reviews:latest
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    env:
      DATABASE_URL: "postgres://marginalia:{{ MARGINALIA_POSTGRES_PASSWORD }}@marginalia-postgres:5432/marginalia?sslmode=disable"
      SECRET_ENCRYPTION_KEY: "{{ MARGINALIA_SECRET_ENCRYPTION_KEY }}"
      HARDCOVER_TOKEN: "{{ MARGINALIA_HARDCOVER_TOKEN }}"
      HARDCOVER_ENABLED: "true"
