---
- name: NGINX-PROXY-MANAGER - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0777"
  loop:
    - "{{ base_dir }}/nginx-proxy-manager"
    - "{{ base_dir }}/letsencrypt"

- name: NGINX-PROXY-MANAGER - Create container
  community.docker.docker_container:
    name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - '{{ base_dir }}/nginx-proxy-manager:/data'
      - '{{ base_dir }}/letsencrypt:/etc/letsencrypt'