---
- name: OPEN BOOKS - Create container
  community.docker.docker_container:
    name: open_books
    image: evanbuss/openbooks
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "8080:80"
    volumes:
      - "/mnt/media/books:/books"
    command: --persist -n CupcakeCreator

- name: OPENBOOKS - Define service entry
  ansible.builtin.set_fact:
    openbooks_entry:
      container: openbooks
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 8080

- name: OPENBOOKS - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ (docker_services | default([])) + [openbooks_entry] }}"
