---
- name: OPEN BOOKS - Create container
  community.docker.docker_container:
    name: open_books
    image: evanbuss/openbooks
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "8080:80"
    volumes:
      - "/mnt/media/books:/books"
    command: --persist -n CupcakeCreator

- name: OPEN BOOKS - Set homepage entry
  set_fact:
    docker_services: "{{ (docker_services | default([])) + [ {
      'container': 'openbooks',
      'ip': inventory_hostname,
      'friendly_name': friendly_name,
      'port': 8080,
    } ] }}"
