---
- name: PI-HOLE - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0777"
  loop:
    - "{{ base_dir }}/pi-hole"

- name: PI-HOLE - Create container
  community.docker.docker_container:
    name: pi-hole
    image: pihole/pihole:2025.04.0
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
    volumes:
      - '{{ base_dir }}/pi-hole/data:/etc/pihole'
    env:
      TZ={{ timezone }}
      FTLCONF_webserver_api_password={{ pihole_password }}
      FTLCONF_dns_revServers="true,192.168.0.0/24,192.168.0.1"
      FTLCONF_dns_upstreams="1.1.1.1;8.8.8.8;8.8.4.4"
      FTLCONF_dns_hosts="192.168.0.102 docker.suskins.co.uk;192.168.0.65 homeassistant.suskins.co.uk;192.168.0.101 mediaserver.suskins.co.uk;192.168.0.100 nas.suskins.co.uk;192.168.0.104 monitor.suskins.co.uk;192.168.0.105 development.suskins.co.uk;192.168.0.103 gameserver.suskins.co.uk;192.168.0.253 proxmox.suskins.co.uk"