---
- name: PI-HOLE-EXPORTER - Create  container
  community.docker.docker_container:
    name: pi-hole-exporter
    image: ekofr/pihole-exporter@sha256:119c511bf3cd0e450826fbefd54bc0c0ec824b12493a7f223ced67a0c6acf327
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "9617:9617"
    env:
      PIHOLE_HOSTNAME=pi-hole
      PIHOLE_PASSWORD={{ pihole_password }}

- name: PI-HOLE-EXPORTER  - Add to scrape configs
  set_fact:
    prometheus_scrape_configs: >-
      {{
        (prometheus_scrape_configs | default([])) +
        [ {
          'job_name': 'pihole',
          'scrape_interval': '60s',
          'static_configs': [ { 'targets': [ ansible_host ~ ':9617' ] } ]
        } ]
      }}