---
- name: PROMTAIL - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0777"
  loop:
    - "{{ base_dir }}/promtail/config"

- name: PROMTAIL - Create config
  ansible.builtin.copy:
    content: |
      server:
        http_listen_port: 9080
        grpc_listen_port: 0

      positions:
        filename: /tmp/positions.yaml

      clients:
        - url: http://192.168.0.104:3100/loki/api/v1/push

      scrape_configs:
        - job_name: flog_scrape
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 5s
          relabel_configs:
            - source_labels: ['__meta_docker_container_name']
              regex: '/(.*)'
              target_label: 'container'
            - source_labels: ['__meta_docker_container_log_stream']
              target_label: 'logstream'
            - source_labels: ['__meta_docker_container_label_logging_jobname']
              target_label: 'job'
    dest: "{{ base_dir }}/promtail/config/config.yml"

- name: PROMTAIL - Create container
  community.docker.docker_container:
    name: promtail
    image: grafana/promtail:3.2.1
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    volumes:
      - "{{ base_dir }}/promtail/config:/etc/promtail"
      - "/var/lib/docker/containers:/var/lib/docker/containers"
      - "/var/run/docker.sock:/var/run/docker.sock"