---
- name: PROMETHEUS - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "65534"
    group: "65534"
    mode: "0755"
  loop:
    - "{{ base_dir }}/prometheus"
    - "{{ base_dir }}/prometheus/config"
    - "{{ base_dir }}/prometheus/data"

- name: PROMETHEUS - Aggregate services from all hosts
  ansible.builtin.include_tasks:
    file: "../tasks/core/aggregate_services.yml"

- name: PROMETHEUS - Create scrape config
  ansible.builtin.template:
    src: ../config/prometheus/config.yml.j2
    dest: "{{ base_dir }}/prometheus/config/prometheus.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
  register: prometheus_config

- name: PROMETHEUS - Remove stale alert rules file
  ansible.builtin.file:
    path: "{{ base_dir }}/prometheus/config/alert.rules.yml"
    state: absent

- name: PROMETHEUS - Pre-pull image
  community.docker.docker_image:
    name: "{{ image }}"
    source: pull
    force_source: true
  vars:
    image: prom/prometheus:v3.14.0

- name: PROMETHEUS - Create container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:v3.14.0
    restart_policy: always
    state: started
    pull: false
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--storage.tsdb.retention.time=90d"
    networks:
      - name: homelab
    ports:
      - "9090:9090"
    volumes:
      - "{{ base_dir }}/prometheus/config:/etc/prometheus"
      - "{{ base_dir }}/prometheus/data:/prometheus"

- name: PROMETHEUS - Restart to apply config changes
  ansible.builtin.command: docker restart prometheus
  when: prometheus_config.changed
  changed_when: true
