---
- name: PROMTAIL - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0777"
  loop:
    - "{{ base_dir }}/promtail/config"

- name: PROMTAIL - Create config
  ansible.builtin.copy:
    src: ../config/promtail/config.yml
    dest: "{{ base_dir }}/promtail/config/config.yml"

- name: PROMTAIL - Create container
  community.docker.docker_container:
    name: promtail
    image: grafana/promtail
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    volumes:
      - "{{ base_dir }}/promtail/config:/etc/promtail"
      - "/var/lib/docker/containers:/var/lib/docker/containers"
      - "/var/run/docker.sock:/var/run/docker.sock"