---
- name: PUBGOLF-BACKEND - Create container
  community.docker.docker_container:
    name: pubgolf_backend
    image: ghcr.io/bensuskins/pubgolf-backend:latest
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - '8080:8080'
    env:
      SPRING_PROFILES_ACTIVE=prod
      DB_HOST=pubgolf_postgres
      DB_USERNAME={{ DB_USERNAME }}
      DB_PASSWORD={{ DB_PASSWORD }}
      DB_PORT=5433