---
- name: PUBGOLF-BACKEND - Add to scrape configs
  ansible.builtin.set_fact:
    prometheus_scrape_configs: >-
      {{
        (prometheus_scrape_configs | default([])) +
        [ {
          'job_name': 'pubgolf',
          'scrape_interval': '60s',
          'metrics_path': '/actuator/prometheus',
          'static_configs': [ { 'targets': [ ansible_host ~ ':8080' ] } ]
        } ]
      }}

- name: PUBGOLF-BACKEND - Create container
  community.docker.docker_container:
    name: pubgolf_backend
    image: ghcr.io/bensuskins/pubgolf-backend:latest
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - '8080:8080'
    env:
      SPRING_PROFILES_ACTIVE=prod
      DB_HOST=pubgolf_postgres
      DB_USERNAME={{ DB_USERNAME }}
      DB_PASSWORD={{ DB_PASSWORD }}
      DB_PORT=5432
