---
- name: PUBGOLF-FRONTEND - Create container
  community.docker.docker_container:
    name: pubgolf_frontend
    image: ghcr.io/bensuskins/pubgolf-frontend:latest
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "3003:3000"
    env:
      NEXT_PUBLIC_API_URL: "https://api.pubgolf.me"

- name: PUBGOLF - Define service entry
  ansible.builtin.set_fact:
    pubgolf_entry:
      container: pubgolf
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 3003

- name: PUBGOLF - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ (docker_services | default([])) + [pubgolf_entry] }}"
