---
- name: REDIS - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    mode: "0755"
  loop:
    - "{{ base_dir }}/redis/data"

- name: REDIS - Pre-pull image
  community.docker.docker_image:
    name: "{{ image }}"
    source: pull
    force_source: true
  vars:
    image: redis:8.10-alpine

- name: REDIS - Create container
  community.docker.docker_container:
    name: redis
    image: redis:8.10-alpine
    restart_policy: always
    state: started
    pull: false
    command: redis-server --appendonly yes
    networks:
      - name: homelab
    volumes:
      - "{{ base_dir }}/redis/data:/data"
    env:
      TZ: "{{ timezone }}"
