name: Deploy with Ansible (Local Runner)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Ansible
        run: |
          ansible-playbook plays/update.yml --vault-password-file ~/.ansible_vault_pass