name: Update Homelab

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Cleanup workspace
        run: rm -rf "${{ github.workspace }}"/*

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Checkout secrets repo
        uses: actions/checkout@v6
        with:
          repository: bensuskins/secrets
          path: secrets
          token: ${{ secrets.SECRETS_REPO_TOKEN }}

      - name: Setup secrets
        run: |
          mkdir -p ~/.ansible
          mv secrets/vault.yml ~/.ansible/vault.yml
          echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > ~/.ansible_vault_pass
          chmod 600 ~/.ansible_vault_pass ~/.ansible/vault.yml

      - name: Run Ansible
        run: |
          ansible-playbook plays/update.yml --vault-password-file ~/.ansible_vault_pass

      - name: Cleanup secrets
        if: always()
        run: |
          rm -f ~/.ansible_vault_pass ~/.ansible/vault.yml
