apiVersion: 1
contactPoints:
  - orgId: 1
    name: grafana-default-email
    receivers:
      - uid: grafana-default-email
        type: email
        settings:
          addresses: root@localhost
          singleEmail: true
